// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrDsDycLBYe4YBNk2vDZFwq4A2WprX_S8',
    appId: '1:180969837015:web:5877bd39cf706824e5fb92',
    messagingSenderId: '180969837015',
    projectId: 'oyo-app-abb71',
    authDomain: 'oyo-app-abb71.firebaseapp.com',
    storageBucket: 'oyo-app-abb71.firebasestorage.app',
    measurementId: 'G-D8RS54G8YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cs7RzUhNlpcvxGDp-lGR-4bxywGDbqI',
    appId: '1:180969837015:android:5887b80315a46bffe5fb92',
    messagingSenderId: '180969837015',
    projectId: 'oyo-app-abb71',
    storageBucket: 'oyo-app-abb71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkpr4f6zi6cQIklV7BvpomWJ7UK8dClUo',
    appId: '1:180969837015:ios:776033ec8ba090b6e5fb92',
    messagingSenderId: '180969837015',
    projectId: 'oyo-app-abb71',
    storageBucket: 'oyo-app-abb71.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkpr4f6zi6cQIklV7BvpomWJ7UK8dClUo',
    appId: '1:180969837015:ios:776033ec8ba090b6e5fb92',
    messagingSenderId: '180969837015',
    projectId: 'oyo-app-abb71',
    storageBucket: 'oyo-app-abb71.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrDsDycLBYe4YBNk2vDZFwq4A2WprX_S8',
    appId: '1:180969837015:web:65d8342ef9a9413ee5fb92',
    messagingSenderId: '180969837015',
    projectId: 'oyo-app-abb71',
    authDomain: 'oyo-app-abb71.firebaseapp.com',
    storageBucket: 'oyo-app-abb71.firebasestorage.app',
    measurementId: 'G-JSEKL33MX5',
  );
}
